App\Infrastructure\Dto\AuthorCreateRequestDto:
  properties:
    name:
      - NotBlank: {message: "нет поле 'name'"}
      - Regex:
          pattern: '/[^\s]$/'
          message: нельзя пробелы в конце и в начале строки поля 'name'
      - Regex:
          pattern: '/[^\d]$/'
          message: нельзя цифры в поле 'name'
      - Length:
          max: 15
          min: 3
          minMessage: "минимальная длина поле 'name' 3 символа"
          maxMessage: "максимальная длина поле 'name' 30 символа"


App\Infrastructure\Dto\BookCreateRequestDto:
  properties:
    name:
      - NotBlank: {message: "нет поле 'name'"}
      - Regex:
          pattern: '/[^\s]$/'
          message: нельзя пробелы в конце и в начале строки поля 'name'
      - Regex:
          pattern: '/[^\d]$/'
          message: нельзя цифры в поле 'name'
      - Length:
          max: 50
          min: 3
          minMessage: "минимальная длина поле 'name' 3 символа"
          maxMessage: "максимальная длина поле 'name' 50 символа"
    authorId:
      - NotBlank: { message: "нет поле 'author_id'" }
      - Regex:
          pattern:  '/(\d)$/'
          message: поле 'author_id' принимает только цифры