doctrine:
    dbal:
        default_connection: airlogic
        connections:
            airlogic:
                url: "pgsql://postgres:root@postgres:5432/airlogic?serverVersion=13&charset=utf8"
                driver: pdo_pgsql

    orm:
        auto_generate_proxy_classes: true
#        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        default_entity_manager: airlogic
#        auto_mapping: true
        entity_managers:
            airlogic:
                connection: airlogic
                mappings:
                    cardsmile:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Infrastructure/Entity/Airlogic'
                        prefix: 'App\Infrastructure\Entity\Airlogic'
                        alias: airlogic

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
