#author
author.create:
  path: /author/create
  controller: App\Infrastructure\Controller\AuthorController::create
  methods: POST

author.serach:
  path: /author/serach
  controller: App\Infrastructure\Controller\AuthorController::search
  methods: GET

#book
book.create:
  path: /book/create
  controller: App\Infrastructure\Controller\BookController::create
  methods: POST

book.info.id:
  path: /{_locale}/book/{id}
  controller: App\Infrastructure\Controller\BookController::bookInfoId
  methods: GET
  requirements:
    id: '\d+'
    _locale: ru|en