#author
author.create:
  path: /author/create
  controller: App\Infrastructure\Controller\AuthorController::create
  methods: POST

#book
book.create:
  path: /book/create
  controller: App\Infrastructure\Controller\BookController::create
  methods: POST