parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude:
            - '../src/Infrastructure/Entity/'
            - '../src/Kernel.php'

    JMS\Serializer\SerializerBuilder:
        autowire: false

    App\Infrastructure\Repository\BaseRepository\AbstractRepository:
        autowire: false
        arguments:

    Dejurin\GoogleTranslateForFree:
        autowire: false


    # listener
    App\Infrastructure\EventListener\Views\Views:
        tags:
            - { name: kernel.event_listener, event: kernel.view }

    App\Infrastructure\EventListener\Request\RequestListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request }
